//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES_BackupManager.ESBackupServerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ESBackupServerService.IESBackupServerService")]
    public interface IESBackupServerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerService/TestConnection", ReplyAction="http://tempuri.org/IESBackupServerService/TestConnectionResponse")]
        string TestConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerService/TestConnection", ReplyAction="http://tempuri.org/IESBackupServerService/TestConnectionResponse")]
        System.Threading.Tasks.Task<string> TestConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerService/Login", ReplyAction="http://tempuri.org/IESBackupServerService/LoginResponse")]
        System.Nullable<System.Guid> Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerService/Login", ReplyAction="http://tempuri.org/IESBackupServerService/LoginResponse")]
        System.Threading.Tasks.Task<System.Nullable<System.Guid>> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerService/Logout", ReplyAction="http://tempuri.org/IESBackupServerService/LogoutResponse")]
        bool Logout(System.Guid sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerService/Logout", ReplyAction="http://tempuri.org/IESBackupServerService/LogoutResponse")]
        System.Threading.Tasks.Task<bool> LogoutAsync(System.Guid sessionID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IESBackupServerServiceChannel : ES_BackupManager.ESBackupServerService.IESBackupServerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ESBackupServerServiceClient : System.ServiceModel.ClientBase<ES_BackupManager.ESBackupServerService.IESBackupServerService>, ES_BackupManager.ESBackupServerService.IESBackupServerService {
        
        public ESBackupServerServiceClient() {
        }
        
        public ESBackupServerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ESBackupServerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ESBackupServerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ESBackupServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestConnection() {
            return base.Channel.TestConnection();
        }
        
        public System.Threading.Tasks.Task<string> TestConnectionAsync() {
            return base.Channel.TestConnectionAsync();
        }
        
        public System.Nullable<System.Guid> Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<System.Guid>> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public bool Logout(System.Guid sessionID) {
            return base.Channel.Logout(sessionID);
        }
        
        public System.Threading.Tasks.Task<bool> LogoutAsync(System.Guid sessionID) {
            return base.Channel.LogoutAsync(sessionID);
        }
    }
}
