//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES_BackupManager.ESBackupServerAdminService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/ESBackupServer.Database.Objects")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ES_BackupManager.ESBackupServerAdminService.Backup[] BackupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> IDLastDifferentialBackupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> IDLastFullBackupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ES_BackupManager.ESBackupServerAdminService.Backup LastDifferentialBackupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ES_BackupManager.ESBackupServerAdminService.Backup LastFullBackupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ES_BackupManager.ESBackupServerAdminService.Login[] LoginsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ES_BackupManager.ESBackupServerAdminService.Log[] LogsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VerifiedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ES_BackupManager.ESBackupServerAdminService.Backup[] Backups {
            get {
                return this.BackupsField;
            }
            set {
                if ((object.ReferenceEquals(this.BackupsField, value) != true)) {
                    this.BackupsField = value;
                    this.RaisePropertyChanged("Backups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> IDLastDifferentialBackup {
            get {
                return this.IDLastDifferentialBackupField;
            }
            set {
                if ((this.IDLastDifferentialBackupField.Equals(value) != true)) {
                    this.IDLastDifferentialBackupField = value;
                    this.RaisePropertyChanged("IDLastDifferentialBackup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> IDLastFullBackup {
            get {
                return this.IDLastFullBackupField;
            }
            set {
                if ((this.IDLastFullBackupField.Equals(value) != true)) {
                    this.IDLastFullBackupField = value;
                    this.RaisePropertyChanged("IDLastFullBackup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ES_BackupManager.ESBackupServerAdminService.Backup LastDifferentialBackup {
            get {
                return this.LastDifferentialBackupField;
            }
            set {
                if ((object.ReferenceEquals(this.LastDifferentialBackupField, value) != true)) {
                    this.LastDifferentialBackupField = value;
                    this.RaisePropertyChanged("LastDifferentialBackup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ES_BackupManager.ESBackupServerAdminService.Backup LastFullBackup {
            get {
                return this.LastFullBackupField;
            }
            set {
                if ((object.ReferenceEquals(this.LastFullBackupField, value) != true)) {
                    this.LastFullBackupField = value;
                    this.RaisePropertyChanged("LastFullBackup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ES_BackupManager.ESBackupServerAdminService.Login[] Logins {
            get {
                return this.LoginsField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginsField, value) != true)) {
                    this.LoginsField = value;
                    this.RaisePropertyChanged("Logins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ES_BackupManager.ESBackupServerAdminService.Log[] Logs {
            get {
                return this.LogsField;
            }
            set {
                if ((object.ReferenceEquals(this.LogsField, value) != true)) {
                    this.LogsField = value;
                    this.RaisePropertyChanged("Logs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Verified {
            get {
                return this.VerifiedField;
            }
            set {
                if ((this.VerifiedField.Equals(value) != true)) {
                    this.VerifiedField = value;
                    this.RaisePropertyChanged("Verified");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Backup", Namespace="http://schemas.datacontract.org/2004/07/ESBackupServer.Database.Objects")]
    [System.SerializableAttribute()]
    public partial class Backup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ES_BackupManager.ESBackupServerAdminService.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CompressedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ES_BackupManager.ESBackupServerAdminService.Client IDClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ES_BackupManager.ESBackupServerAdminService.Log[] LogsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TimeEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeStartField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ES_BackupManager.ESBackupServerAdminService.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Compressed {
            get {
                return this.CompressedField;
            }
            set {
                if ((this.CompressedField.Equals(value) != true)) {
                    this.CompressedField = value;
                    this.RaisePropertyChanged("Compressed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpirationDate {
            get {
                return this.ExpirationDateField;
            }
            set {
                if ((this.ExpirationDateField.Equals(value) != true)) {
                    this.ExpirationDateField = value;
                    this.RaisePropertyChanged("ExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ES_BackupManager.ESBackupServerAdminService.Client IDClient {
            get {
                return this.IDClientField;
            }
            set {
                if ((object.ReferenceEquals(this.IDClientField, value) != true)) {
                    this.IDClientField = value;
                    this.RaisePropertyChanged("IDClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ES_BackupManager.ESBackupServerAdminService.Log[] Logs {
            get {
                return this.LogsField;
            }
            set {
                if ((object.ReferenceEquals(this.LogsField, value) != true)) {
                    this.LogsField = value;
                    this.RaisePropertyChanged("Logs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TimeEnd {
            get {
                return this.TimeEndField;
            }
            set {
                if ((this.TimeEndField.Equals(value) != true)) {
                    this.TimeEndField = value;
                    this.RaisePropertyChanged("TimeEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStart {
            get {
                return this.TimeStartField;
            }
            set {
                if ((this.TimeStartField.Equals(value) != true)) {
                    this.TimeStartField = value;
                    this.RaisePropertyChanged("TimeStart");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Login", Namespace="http://schemas.datacontract.org/2004/07/ESBackupServer.Database.Objects")]
    [System.SerializableAttribute()]
    public partial class Login : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ES_BackupManager.ESBackupServerAdminService.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UTCTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ES_BackupManager.ESBackupServerAdminService.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDClient {
            get {
                return this.IDClientField;
            }
            set {
                if ((this.IDClientField.Equals(value) != true)) {
                    this.IDClientField = value;
                    this.RaisePropertyChanged("IDClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UTCTime {
            get {
                return this.UTCTimeField;
            }
            set {
                if ((this.UTCTimeField.Equals(value) != true)) {
                    this.UTCTimeField = value;
                    this.RaisePropertyChanged("UTCTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Log", Namespace="http://schemas.datacontract.org/2004/07/ESBackupServer.Database.Objects")]
    [System.SerializableAttribute()]
    public partial class Log : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ES_BackupManager.ESBackupServerAdminService.Backup BackupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ES_BackupManager.ESBackupServerAdminService.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> IDBackupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte IDLogTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ES_BackupManager.ESBackupServerAdminService.LogType LogTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UTCTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ES_BackupManager.ESBackupServerAdminService.Backup Backup {
            get {
                return this.BackupField;
            }
            set {
                if ((object.ReferenceEquals(this.BackupField, value) != true)) {
                    this.BackupField = value;
                    this.RaisePropertyChanged("Backup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ES_BackupManager.ESBackupServerAdminService.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> IDBackup {
            get {
                return this.IDBackupField;
            }
            set {
                if ((this.IDBackupField.Equals(value) != true)) {
                    this.IDBackupField = value;
                    this.RaisePropertyChanged("IDBackup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDClient {
            get {
                return this.IDClientField;
            }
            set {
                if ((this.IDClientField.Equals(value) != true)) {
                    this.IDClientField = value;
                    this.RaisePropertyChanged("IDClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte IDLogType {
            get {
                return this.IDLogTypeField;
            }
            set {
                if ((this.IDLogTypeField.Equals(value) != true)) {
                    this.IDLogTypeField = value;
                    this.RaisePropertyChanged("IDLogType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ES_BackupManager.ESBackupServerAdminService.LogType LogType {
            get {
                return this.LogTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.LogTypeField, value) != true)) {
                    this.LogTypeField = value;
                    this.RaisePropertyChanged("LogType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UTCTime {
            get {
                return this.UTCTimeField;
            }
            set {
                if ((this.UTCTimeField.Equals(value) != true)) {
                    this.UTCTimeField = value;
                    this.RaisePropertyChanged("UTCTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogType", Namespace="http://schemas.datacontract.org/2004/07/ESBackupServer.Database.Objects")]
    [System.SerializableAttribute()]
    public partial class LogType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ES_BackupManager.ESBackupServerAdminService.Log[] LogsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ES_BackupManager.ESBackupServerAdminService.LogTypeNames NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ES_BackupManager.ESBackupServerAdminService.Log[] Logs {
            get {
                return this.LogsField;
            }
            set {
                if ((object.ReferenceEquals(this.LogsField, value) != true)) {
                    this.LogsField = value;
                    this.RaisePropertyChanged("Logs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ES_BackupManager.ESBackupServerAdminService.LogTypeNames Name {
            get {
                return this.NameField;
            }
            set {
                if ((this.NameField.Equals(value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogTypeNames", Namespace="http://schemas.datacontract.org/2004/07/ESBackupServer.Database.Objects")]
    public enum LogTypeNames : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Message = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Configuration", Namespace="http://schemas.datacontract.org/2004/07/ESBackupServer.App.Objects")]
    [System.SerializableAttribute()]
    public partial class Configuration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ESBackupServerAdminService.IESBackupServerAdminService")]
    public interface IESBackupServerAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerAdminService/GetClients", ReplyAction="http://tempuri.org/IESBackupServerAdminService/GetClientsResponse")]
        ES_BackupManager.ESBackupServerAdminService.Client[] GetClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerAdminService/GetClients", ReplyAction="http://tempuri.org/IESBackupServerAdminService/GetClientsResponse")]
        System.Threading.Tasks.Task<ES_BackupManager.ESBackupServerAdminService.Client[]> GetClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerAdminService/GetBackups", ReplyAction="http://tempuri.org/IESBackupServerAdminService/GetBackupsResponse")]
        ES_BackupManager.ESBackupServerAdminService.Backup[] GetBackups(ES_BackupManager.ESBackupServerAdminService.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerAdminService/GetBackups", ReplyAction="http://tempuri.org/IESBackupServerAdminService/GetBackupsResponse")]
        System.Threading.Tasks.Task<ES_BackupManager.ESBackupServerAdminService.Backup[]> GetBackupsAsync(ES_BackupManager.ESBackupServerAdminService.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerAdminService/GetLogs", ReplyAction="http://tempuri.org/IESBackupServerAdminService/GetLogsResponse")]
        ES_BackupManager.ESBackupServerAdminService.Log[] GetLogs(ES_BackupManager.ESBackupServerAdminService.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerAdminService/GetLogs", ReplyAction="http://tempuri.org/IESBackupServerAdminService/GetLogsResponse")]
        System.Threading.Tasks.Task<ES_BackupManager.ESBackupServerAdminService.Log[]> GetLogsAsync(ES_BackupManager.ESBackupServerAdminService.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerAdminService/GetConfiguration", ReplyAction="http://tempuri.org/IESBackupServerAdminService/GetConfigurationResponse")]
        ES_BackupManager.ESBackupServerAdminService.Configuration GetConfiguration(ES_BackupManager.ESBackupServerAdminService.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerAdminService/GetConfiguration", ReplyAction="http://tempuri.org/IESBackupServerAdminService/GetConfigurationResponse")]
        System.Threading.Tasks.Task<ES_BackupManager.ESBackupServerAdminService.Configuration> GetConfigurationAsync(ES_BackupManager.ESBackupServerAdminService.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerAdminService/SaveConfiguration", ReplyAction="http://tempuri.org/IESBackupServerAdminService/SaveConfigurationResponse")]
        bool SaveConfiguration(ES_BackupManager.ESBackupServerAdminService.Client client, ES_BackupManager.ESBackupServerAdminService.Configuration config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerAdminService/SaveConfiguration", ReplyAction="http://tempuri.org/IESBackupServerAdminService/SaveConfigurationResponse")]
        System.Threading.Tasks.Task<bool> SaveConfigurationAsync(ES_BackupManager.ESBackupServerAdminService.Client client, ES_BackupManager.ESBackupServerAdminService.Configuration config);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IESBackupServerAdminServiceChannel : ES_BackupManager.ESBackupServerAdminService.IESBackupServerAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ESBackupServerAdminServiceClient : System.ServiceModel.ClientBase<ES_BackupManager.ESBackupServerAdminService.IESBackupServerAdminService>, ES_BackupManager.ESBackupServerAdminService.IESBackupServerAdminService {
        
        public ESBackupServerAdminServiceClient() {
        }
        
        public ESBackupServerAdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ESBackupServerAdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ESBackupServerAdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ESBackupServerAdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ES_BackupManager.ESBackupServerAdminService.Client[] GetClients() {
            return base.Channel.GetClients();
        }
        
        public System.Threading.Tasks.Task<ES_BackupManager.ESBackupServerAdminService.Client[]> GetClientsAsync() {
            return base.Channel.GetClientsAsync();
        }
        
        public ES_BackupManager.ESBackupServerAdminService.Backup[] GetBackups(ES_BackupManager.ESBackupServerAdminService.Client client) {
            return base.Channel.GetBackups(client);
        }
        
        public System.Threading.Tasks.Task<ES_BackupManager.ESBackupServerAdminService.Backup[]> GetBackupsAsync(ES_BackupManager.ESBackupServerAdminService.Client client) {
            return base.Channel.GetBackupsAsync(client);
        }
        
        public ES_BackupManager.ESBackupServerAdminService.Log[] GetLogs(ES_BackupManager.ESBackupServerAdminService.Client client) {
            return base.Channel.GetLogs(client);
        }
        
        public System.Threading.Tasks.Task<ES_BackupManager.ESBackupServerAdminService.Log[]> GetLogsAsync(ES_BackupManager.ESBackupServerAdminService.Client client) {
            return base.Channel.GetLogsAsync(client);
        }
        
        public ES_BackupManager.ESBackupServerAdminService.Configuration GetConfiguration(ES_BackupManager.ESBackupServerAdminService.Client client) {
            return base.Channel.GetConfiguration(client);
        }
        
        public System.Threading.Tasks.Task<ES_BackupManager.ESBackupServerAdminService.Configuration> GetConfigurationAsync(ES_BackupManager.ESBackupServerAdminService.Client client) {
            return base.Channel.GetConfigurationAsync(client);
        }
        
        public bool SaveConfiguration(ES_BackupManager.ESBackupServerAdminService.Client client, ES_BackupManager.ESBackupServerAdminService.Configuration config) {
            return base.Channel.SaveConfiguration(client, config);
        }
        
        public System.Threading.Tasks.Task<bool> SaveConfigurationAsync(ES_BackupManager.ESBackupServerAdminService.Client client, ES_BackupManager.ESBackupServerAdminService.Configuration config) {
            return base.Channel.SaveConfigurationAsync(client, config);
        }
    }
}
